import Link from "next/link";
import {requireRole} from "@/lib/auth/server";
import {createClient} from "@/lib/supabase/server";
export default async function Page({searchParams}:{searchParams:Promise<{scholarship?:string}>}){
 await requireRole(["staff"]);const f=await searchParams,c=await createClient();
 const [a,r,e,p,k,s]=await Promise.all([c.from("applications").select("id,application_no,student_name,scholarship_id"),c.from("review_assignments").select("id,application_id,reviewer_id,status"),c.from("evaluations").select("assignment_id,scores,total_score,recommendation,comment,submitted_at"),c.from("portal_profiles").select("id,full_name").eq("role","committee"),c.from("scholarship_review_criteria").select("id,label,max_score,scholarship_id").order("sort_order"),c.from("scholarships").select("id,title,required_reviewer_count")]);
 if(a.error||r.error||e.error||p.error||k.error||s.error)throw Error("โหลดผลประเมินไม่ได้");
 return <div className="workflow-stack"><section className="panel"><h1>สรุปคะแนนกรรมการ</h1><p>คะแนนเฉลี่ยคำนวณเฉพาะผลที่ส่งแล้ว งานถอนและฉบับร่างไม่นับรวม</p><form><label>ทุน<select name="scholarship" defaultValue={f.scholarship??""}><option value="">ทุกทุน</option>{s.data.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><div className="evaluation-filter-actions"><button className="btn">กรอง</button></div></form></section>
 {a.data.filter(x=>(!f.scholarship||x.scholarship_id===f.scholarship)&&r.data.some(r=>r.application_id===x.id)).map(app=>{
 const assignments=r.data.filter(x=>x.application_id===app.id&&x.status!=="revoked");
 const submitted=assignments.filter(x=>x.status==="completed").flatMap(x=>e.data.filter(e=>e.assignment_id===x.id&&e.submitted_at));
 const criteria=k.data.filter(x=>x.scholarship_id===app.scholarship_id);
 return <section className="panel" key={app.id}><h2>#{app.application_no} · {app.student_name}</h2><p>{s.data.find(x=>x.id===app.scholarship_id)?.title} · ส่งแล้ว {submitted.length}/{assignments.length} · ขั้นต่ำ {s.data.find(x=>x.id===app.scholarship_id)?.required_reviewer_count}</p><p>เฉลี่ยรวม: {submitted.length?(submitted.reduce((n,e)=>n+Number(e.total_score),0)/submitted.length).toFixed(2):"ยังไม่มีคะแนน"}</p>
 <div style={{overflowX:"auto"}}><table className="review-score-table"><thead><tr><th>กรรมการ</th>{criteria.map(k=><th key={k.id}>{k.label} / {k.max_score}</th>)}<th>รวม</th><th>ข้อเสนอ / ความเห็น</th></tr></thead><tbody>{assignments.map(x=>{const ev=e.data.find(e=>e.assignment_id===x.id&&e.submitted_at);const scores=(ev?.scores??[]) as {criterion_id:string;score:number}[];return <tr key={x.id}><td>{p.data.find(p=>p.id===x.reviewer_id)?.full_name??"กรรมการ"}</td>{criteria.map(k=><td key={k.id}>{scores.find(s=>s.criterion_id===k.id)?.score??"—"}</td>)}<td>{ev?.total_score??"ยังไม่ส่ง"}</td><td>{ev?({approve:"เสนออนุมัติ",reserve:"เสนอสำรอง",reject:"ไม่เสนออนุมัติ"}[ev.recommendation as "approve"]):"รอผล"} {ev?.comment}</td></tr>})}</tbody><tfoot><tr><th>เฉลี่ยรายเกณฑ์</th>{criteria.map(k=>{const values=submitted.flatMap(e=>(e.scores as {criterion_id:string;score:number}[]).filter(s=>s.criterion_id===k.id).map(s=>Number(s.score)));return <td key={k.id}>{values.length?(values.reduce((a,b)=>a+b,0)/values.length).toFixed(2):"—"}</td>;})}<td colSpan={2}>เฉพาะคะแนนที่ส่งแล้ว</td></tr></tfoot></table></div><Link href={"/staff/evaluations/"+app.id}>เปิดหน้าสรุปและตัดสินผล</Link></section>})}</div>;
}
