import Link from "next/link";
import { notFound } from "next/navigation";
import { getScholarship } from "@/lib/scholarships/server";
import { money, scholarshipCoverUrl, thaiDate } from "@/lib/scholarships/types";
import { ScholarshipStatusBadge } from "@/components/workflow/StatusBadge";

export default async function ScholarshipDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const scholarship = await getScholarship(id);
  if (!scholarship) notFound();
  return <div className="workflow-stack"><section className="panel workflow-heading"><div><span className="workflow-eyebrow">SCHOLARSHIP DETAIL</span><h1>{scholarship.title}</h1><p>เปิดรับ {thaiDate(scholarship.opens_at, true)} ถึง {thaiDate(scholarship.closes_at, true)}</p></div><ScholarshipStatusBadge status={scholarship.status}/></section><section className="panel">{scholarshipCoverUrl(scholarship.cover_path) && <div className="workflow-scholarship-cover detail" role="img" aria-label={`ภาพประกอบ ${scholarship.title}`} style={{ backgroundImage: `url("${scholarshipCoverUrl(scholarship.cover_path)}")` }}/>}<div className="workflow-facts"><div><span>มูลค่าต่อทุน</span><strong>{money(scholarship.amount)} บาท</strong></div><div><span>จำนวนทุน</span><strong>{scholarship.quota} คน</strong></div><div><span>GPA ขั้นต่ำ</span><strong>{scholarship.minimum_gpa?.toFixed(2) ?? "ไม่กำหนด"}</strong></div></div><h2>รายละเอียด</h2><p className="workflow-preserve">{scholarship.description || "ไม่มีรายละเอียดเพิ่มเติม"}</p><h2>คุณสมบัติและเงื่อนไข</h2><p className="workflow-preserve">{scholarship.eligibility || "ไม่มีเงื่อนไขเพิ่มเติม"}</p></section><section className="panel"><h2>เอกสารประกอบ</h2><ul className="workflow-checklist">{scholarship.requirements.map((item) => <li key={item.id}><strong>{item.label}</strong>{item.required && <span className="required-mark">จำเป็น</span>}<small>{item.details}</small></li>)}</ul></section><section className="panel"><h2>หลักเกณฑ์การพิจารณา</h2><div className="workflow-score-table"><table><thead><tr><th>เกณฑ์</th><th>คะแนนเต็ม</th></tr></thead><tbody>{scholarship.criteria.map((item) => <tr key={item.id}><td><strong>{item.label}</strong>{item.details && <small>{item.details}</small>}</td><td>{item.max_score}</td></tr>)}</tbody></table></div></section><div className="workflow-actions"><Link className="btn secondary" href="/scholarships">กลับรายการทุน</Link><Link className="btn secondary" href={`/scholarships/${scholarship.id}/results`}>ตรวจประกาศผล</Link><Link className="btn" href={`/apply?scholarship=${scholarship.id}`}>เริ่มสมัครทุนนี้</Link></div></div>;
}
