import Link from "next/link";
import { notFound } from "next/navigation";
import { requireRole } from "@/lib/auth/server";
import { getStudentApplicationDetail } from "@/lib/scholarships/server";
import { money, thaiDate } from "@/lib/scholarships/types";
import { ApplicationStatusBadge } from "@/components/workflow/StatusBadge";

export default async function ApplicationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireRole(["student"]);
  const { id } = await params;
  const detail = await getStudentApplicationDetail(id);
  if (!detail) notFound();
  const { application, scholarship, documents, paymentAccount, disbursement, history } = detail;
  return <div className="workflow-stack"><section className="panel workflow-heading"><div><span className="workflow-eyebrow">APPLICATION #{application.application_no}</span><h1>{scholarship.title}</h1><p>ยื่นใบสมัคร {application.submitted_at ? thaiDate(application.submitted_at, true) : "ยังไม่ได้ส่ง"}</p></div><ApplicationStatusBadge status={application.status}/></section>{["draft", "revision_requested"].includes(application.status) && <section className="panel workflow-info">คุณยังแก้ไขใบสมัครได้ <Link href={`/apply?scholarship=${scholarship.id}`}>กลับไปแก้ไขใบสมัคร</Link></section>}<section className="panel"><h2>เอกสารประกอบ</h2><div className="workflow-row-list">{documents.map((document) => <Link href={`/documents/${document.id}`} key={document.id}><span><strong>{document.requirement?.label ?? "เอกสาร"}</strong><small>{document.file_name}{document.feedback ? ` · ${document.feedback}` : ""}</small></span><span className={`document-state ${document.status}`}>{document.status === "verified" ? "ผ่านการตรวจ" : document.status === "revision_required" ? "ขอแก้ไข" : "รอตรวจ"}</span></Link>)}</div></section><section className="panel"><h2>ข้อมูลบัญชีรับเงิน</h2>{paymentAccount ? <div className="workflow-facts"><div><span>ธนาคาร</span><strong>{paymentAccount.bank_name}</strong></div><div><span>ชื่อบัญชี</span><strong>{paymentAccount.account_holder}</strong></div><div><span>เลขบัญชี</span><strong>{paymentAccount.account_number}</strong></div></div> : <p>ยังไม่ได้ระบุข้อมูลบัญชี</p>}</section>{disbursement && <section className="panel"><h2>สถานะการจ่ายทุน</h2><div className="workflow-facts"><div><span>จำนวนเงิน</span><strong>{money(disbursement.amount)} บาท</strong></div><div><span>สถานะ</span><strong>{disbursement.status === "paid" ? "จ่ายแล้ว" : disbursement.status === "failed" ? "โอนไม่สำเร็จ" : "รอดำเนินการ"}</strong></div>{disbursement.transfer_date && <div><span>วันที่โอน</span><strong>{thaiDate(disbursement.transfer_date)}</strong></div>}{disbursement.transfer_reference && <div><span>เลขอ้างอิง</span><strong>{disbursement.transfer_reference}</strong></div>}</div>{disbursement.proof_path && <p><Link className="btn secondary" href={`/disbursements/${disbursement.id}/proof`}>ดาวน์โหลดหลักฐานการโอน</Link></p>}</section>}<section className="panel"><h2>ประวัติการดำเนินการ</h2><ol className="workflow-timeline">{history.map((entry) => <li key={entry.id}><time>{thaiDate(entry.created_at, true)}</time><strong>{entry.from_status ? `${entry.from_status} → ${entry.to_status}` : entry.to_status}</strong>{entry.reason && <p>{entry.reason}</p>}</li>)}</ol></section><div className="workflow-actions"><Link className="btn secondary" href="/applications">กลับรายการใบสมัคร</Link></div></div>;
}
